"""
Layer 3 → Template Schema Transformation

This script transforms the raw Layer 3 JSON output into the schema
expected by the Fairbridge memo template.

Usage:
    python transform_layer3_to_schema.py layer3_data.json output_schema.json
"""

import json
from typing import Any, Dict, List, Optional
from datetime import datetime


def format_currency(value: Optional[float]) -> str:
    """Format number as currency string."""
    if value is None:
        return "N/A"
    return f"${value:,.0f}"


def format_percent(value: Optional[float]) -> str:
    """Format decimal as percentage string."""
    if value is None:
        return "N/A"
    return f"{value * 100:.1f}%"


def format_date(date_str: Optional[str]) -> str:
    """Format date string."""
    if not date_str:
        return "N/A"
    try:
        # Try parsing ISO format
        dt = datetime.fromisoformat(date_str.replace('Z', '+00:00'))
        return dt.strftime("%B %d, %Y")
    except:
        return date_str


def transform_foreclosure_row(row: Dict, quarter_num: int) -> Dict[str, str]:
    """Transform a foreclosure projection row to template format."""
    return {
        "Quarter": f"Q{quarter_num}",
        "Beginning_Balance": format_currency(row.get("beginning_balance")),
        "Legal_Fees": format_currency(row.get("legal_fees")),
        "Taxes": format_currency(row.get("tax_payment")),
        "Insurance": format_currency(row.get("insurance_payment")),
        "Total_Carrying_Costs": format_currency(row.get("total_carrying_costs")),
        "Interest_Accrued": format_currency(row.get("interest_accrued")),
        "Ending_Balance": format_currency(row.get("ending_balance")),
        "Property_Value": format_currency(row.get("property_value")),
        "LTV": format_percent(row.get("ltv"))
    }


def transform_layer3_to_schema(layer3: Dict[str, Any]) -> Dict[str, Any]:
    """
    Transform Layer 3 output to template-ready schema.

    Args:
        layer3: The raw Layer 3 JSON data

    Returns:
        Schema-compliant dict ready for template rendering
    """

    # Extract commonly used sections
    deal_id = layer3.get("deal_identification", {})
    extracted = layer3.get("extracted_data", {})
    deal_ready = layer3.get("deal_memo_ready", {})
    foreclosure = deal_ready.get("default_analysis", {})
    risk = layer3.get("risk_analysis", {})

    # Build the schema
    schema = {
        "schema_version": "fairbridge_memo_v1",
        "meta": {
            "deal_id": layer3.get("meta", {}).get("deal_id"),
            "generated_at": datetime.now().isoformat(),
            "source_layer3_timestamp": layer3.get("meta", {}).get("processing_completed")
        },

        # =========================================
        # COVER PAGE
        # =========================================
        "cover": {
            "memo_title": "INVESTMENT MEMORANDUM",
            "property_name": extracted.get("site_plan", {}).get("data", {}).get("project_name", "Property Name"),
            "property_address": deal_id.get("property_address", ""),
            "borrower": deal_id.get("borrower", ""),
            "credit_committee": deal_id.get("sponsor_names", []),
            "memo_date": datetime.now().strftime("%B %d, %Y")
        },

        # =========================================
        # TABLE OF CONTENTS
        # =========================================
        "toc": None,  # Generated by Word native TOC

        # =========================================
        # SECTIONS
        # =========================================
        "sections": {}
    }

    sections = schema["sections"]

    # -----------------------------------------
    # 1. TRANSACTION OVERVIEW
    # -----------------------------------------
    loan_terms = extracted.get("loan_terms", {}).get("data", {})
    deal_facts = deal_ready.get("deal_facts_table", {})
    leverage = deal_ready.get("leverage_ratios_table", {})

    sections["transaction_overview"] = {
        "deal_facts": [
            {"label": "Property Address", "value": deal_facts.get("property_address", "")},
            {"label": "Property Type", "value": deal_facts.get("property_type", "")},
            {"label": "Loan Amount", "value": deal_facts.get("loan_amount", "")},
            {"label": "Loan Term", "value": deal_facts.get("loan_term", "")},
            {"label": "Interest Rate", "value": loan_terms.get("interest_rate") or deal_facts.get("interest_rate") or "N/A"},
            {"label": "Origination Fee", "value": deal_facts.get("origination_fee", "")},
            {"label": "Exit Fee", "value": deal_facts.get("exit_fee", "")},
            {"label": "Extension Options", "value": deal_facts.get("extension_options", "")},
            {"label": "Recourse", "value": deal_facts.get("recourse", "")},
            {"label": "Borrower", "value": deal_facts.get("borrower", "")},
            {"label": "Guarantors", "value": deal_facts.get("guarantors", "")}
        ],
        "loan_terms": [
            {"label": "Loan Amount", "value": format_currency(loan_terms.get("loan_amount"))},
            {"label": "Loan at Closing", "value": format_currency(loan_terms.get("loan_amount_at_closing"))},
            {"label": "Loan at Maturity", "value": format_currency(loan_terms.get("loan_amount_at_maturity"))},
            {"label": "Term", "value": f"{loan_terms.get('loan_term_months', 'N/A')} months"},
            {"label": "Interest Rate", "value": loan_terms.get("interest_rate", "N/A")},
            {"label": "Spread over Index", "value": f"{loan_terms.get('spread_over_index', 'N/A')} bps"},
            {"label": "Index Floor", "value": format_percent(loan_terms.get("index_floor"))},
            {"label": "Origination Fee", "value": format_percent(loan_terms.get("origination_fee_percent"))},
            {"label": "Exit Fee", "value": format_percent(loan_terms.get("exit_fee_percent"))},
            {"label": "Extensions", "value": loan_terms.get("extension_options", "N/A")},
            {"label": "Recourse", "value": loan_terms.get("recourse_type", "N/A")}
        ],
        "leverage_metrics": [
            {"label": "LTC at Closing", "value": leverage.get("ltc_at_closing", "N/A")},
            {"label": "LTV at Closing", "value": leverage.get("ltv_at_closing", "N/A")},
            {"label": "LTV at Maturity", "value": leverage.get("ltv_at_maturity", "N/A")},
            {"label": "Debt Yield", "value": leverage.get("debt_yield", "N/A")}
        ]
    }

    # -----------------------------------------
    # 2. EXECUTIVE SUMMARY
    # -----------------------------------------
    narratives = deal_ready.get("narrative_placeholders", {})

    sections["executive_summary"] = {
        "narrative": narratives.get("deal_summary", "[Executive summary to be generated]"),
        "key_highlights": [
            f"${loan_terms.get('loan_amount', 0):,.0f} bridge loan for {extracted.get('appraisal', {}).get('data', {}).get('gross_building_area_sf', 0):,.0f} SF retail center",
            f"Conservative LTV at closing of {leverage.get('ltv_at_closing', 'N/A')}",
            f"Experienced sponsor with {deal_ready.get('sponsor_summary', {}).get('net_worth', 'N/A')} net worth",
            "Interest reserve funded at closing",
            "Multiple exit strategies available"
        ],
        "recommendation": risk.get("overall_risk_score", {}).get("recommendation", ""),
        "conditions": []
    }

    # -----------------------------------------
    # 3. SOURCES & USES
    # -----------------------------------------
    su_table = deal_ready.get("sources_uses_table", {})

    sections["sources_and_uses"] = {
        "fairbridge_sources_uses": {
            "sources": [
                {"label": "Senior Loan", "value": su_table.get("sources", {}).get("senior_loan", "N/A")},
                {"label": "Sponsor Equity", "value": su_table.get("sources", {}).get("sponsor_equity", "N/A")},
                {"label": "Total Sources", "value": su_table.get("sources", {}).get("total_sources", "N/A")}
            ],
            "uses": [
                {"label": "Refinance Existing Debt", "value": su_table.get("uses", {}).get("refinance_existing_debt", "N/A")},
                {"label": "Interest Reserve", "value": su_table.get("uses", {}).get("interest_reserve", "N/A")},
                {"label": "Pre-Development Costs", "value": su_table.get("uses", {}).get("pre_development_costs", "N/A")},
                {"label": "Total Uses", "value": su_table.get("uses", {}).get("total_uses", "N/A")}
            ]
        },
        "holdbacks_detail": [],
        "reserves_detail": []
    }

    # Add holdbacks if present
    for holdback in loan_terms.get("holdbacks", []):
        sections["sources_and_uses"]["holdbacks_detail"].append({
            "name": holdback.get("name", ""),
            "amount": format_currency(holdback.get("amount")),
            "conditions": holdback.get("release_conditions", "")
        })

    # Add reserves if present
    for reserve in loan_terms.get("reserves", []):
        sections["sources_and_uses"]["reserves_detail"].append({
            "name": reserve.get("name", ""),
            "amount": format_currency(reserve.get("amount"))
        })

    # -----------------------------------------
    # 4. PROPERTY
    # -----------------------------------------
    prop_summary = deal_ready.get("property_summary", {})
    appraisal = extracted.get("appraisal", {}).get("data", {})

    sections["property"] = {
        "description_narrative": narratives.get("property_description", "[Property description to be generated]"),
        "metrics": [
            {"label": "Location", "value": prop_summary.get("location", "")},
            {"label": "Property Type", "value": prop_summary.get("property_type", "")},
            {"label": "Year Built", "value": str(prop_summary.get("year_built", "N/A"))},
            {"label": "Site Size", "value": prop_summary.get("site_size", "")},
            {"label": "GLA", "value": prop_summary.get("gla", "")},
            {"label": "Occupancy", "value": prop_summary.get("occupancy", "")},
            {"label": "As-Is Value", "value": prop_summary.get("appraised_value_as_is", "")},
            {"label": "Stabilized Value", "value": prop_summary.get("appraised_value_stabilized", "")},
            {"label": "Appraiser", "value": prop_summary.get("appraiser", "")}
        ],
        "tenant_summary": None  # Add if tenant data available
    }

    # -----------------------------------------
    # 5. LOCATION
    # -----------------------------------------
    sections["location"] = {
        "narrative": narratives.get("location_overview", "[Location overview to be generated]"),
        "highlights": [],
        "demographics": None
    }

    # -----------------------------------------
    # 6. MARKET (CONDITIONAL)
    # -----------------------------------------
    sections["market"] = {
        "enabled": False,  # Requires CoStar/Green Street enrichment
        "narrative": narratives.get("market_overview", "[Market overview requires enrichment data]"),
        "bullets": [],
        "submarket_metrics": []
    }

    # -----------------------------------------
    # 7. BUSINESS PLAN
    # -----------------------------------------
    sections["business_plan"] = {
        "narrative": narratives.get("business_plan", "[Business plan to be generated]"),
        "milestones": []
    }

    # -----------------------------------------
    # 8. SPONSORSHIP
    # -----------------------------------------
    sponsor = deal_ready.get("sponsor_summary", {})

    sections["sponsorship"] = {
        "overview_narrative": sponsor.get("experience", "[Sponsor overview to be generated]"),
        "principals": [
            {
                "name": sponsor.get("names", ""),
                "entity": sponsor.get("entity", ""),
                "role": "Sponsor/Guarantor"
            }
        ],
        "financial_summary": [
            {"label": "Credit Score", "value": str(sponsor.get("credit_score", "N/A"))},
            {"label": "Net Worth", "value": sponsor.get("net_worth", "N/A")},
            {"label": "Equity at Risk", "value": sponsor.get("equity_at_risk") or "N/A"}
        ],
        "track_record": []
    }

    # -----------------------------------------
    # 9. THIRD-PARTY REPORTS
    # -----------------------------------------
    tpr = deal_ready.get("third_party_reviews", {})

    sections["third_party_reports"] = {
        "appraisal": {
            "firm": tpr.get("appraisal", {}).get("firm", ""),
            "appraiser": tpr.get("appraisal", {}).get("appraiser", ""),
            "effective_date": tpr.get("appraisal", {}).get("effective_date", ""),
            "as_is_value": tpr.get("appraisal", {}).get("as_is_value", ""),
            "stabilized_value": tpr.get("appraisal", {}).get("stabilized_value", ""),
            "cap_rate": tpr.get("appraisal", {}).get("cap_rate", "")
        },
        "environmental": {
            "firm": tpr.get("environmental", {}).get("firm", ""),
            "professional": tpr.get("environmental", {}).get("professional", ""),
            "report_date": tpr.get("environmental", {}).get("report_date", ""),
            "findings": tpr.get("environmental", {}).get("findings", ""),
            "recs_count": tpr.get("environmental", {}).get("current_recs", 0),
            "phase_ii_recommended": tpr.get("environmental", {}).get("phase_ii_recommended", False)
        },
        "property_condition": {
            "firm": tpr.get("property_condition", {}).get("firm"),
            "status": tpr.get("property_condition", {}).get("status"),
            "scope": tpr.get("property_condition", {}).get("scope")
        }
    }

    # -----------------------------------------
    # 10. ZONING & ENTITLEMENTS (CONDITIONAL)
    # -----------------------------------------
    sections["zoning_entitlements"] = {
        "enabled": True,  # Enable if site_plan data available
        "summary_narrative": "[Zoning summary to be generated]",
        "key_points": []
    }

    # -----------------------------------------
    # 11. RISKS & MITIGANTS
    # -----------------------------------------
    risk_cats = risk.get("categories", {})
    risk_items = []

    for cat_name, cat_data in risk_cats.items():
        risk_items.append({
            "category": cat_name.replace("_", " ").title(),
            "score": cat_data.get("score", "N/A"),
            "positive_factors": cat_data.get("factors", {}).get("positive", []),
            "negative_factors": cat_data.get("factors", {}).get("negative", []),
            "mitigants": cat_data.get("factors", {}).get("mitigants", [])
        })

    sections["risks_and_mitigants"] = {
        "overall_risk_score": risk.get("overall_risk_score", {}).get("score", "MODERATE"),
        "items": risk_items
    }

    # -----------------------------------------
    # 12. FORECLOSURE ANALYSIS
    # -----------------------------------------
    default_scenario = foreclosure.get("scenario_default_rate", {})
    note_scenario = foreclosure.get("scenario_note_rate", {})
    assumptions = foreclosure.get("assumptions", {})

    sections["foreclosure_analysis"] = {
        "assumptions": [
            {"label": "Loan Amount", "value": format_currency(assumptions.get("loan_amount"))},
            {"label": "Starting Property Value", "value": format_currency(assumptions.get("starting_property_value"))},
            {"label": "Foreclosure Timeline", "value": f"{assumptions.get('foreclosure_timeline_quarters', 12)} quarters"},
            {"label": "Default Interest Rate", "value": format_percent(assumptions.get("default_interest_rate"))},
            {"label": "Note Rate", "value": format_percent(assumptions.get("note_rate"))},
            {"label": "Monthly Taxes", "value": format_currency(assumptions.get("monthly_taxes"))},
            {"label": "Monthly Insurance", "value": format_currency(assumptions.get("monthly_insurance"))},
            {"label": "Monthly Legal Fees", "value": format_currency(assumptions.get("monthly_legal_fees"))}
        ],
        "scenario_default_rate": {
            "name": default_scenario.get("name", "Default Interest Rate"),
            "interest_rate": default_scenario.get("interest_rate", ""),
            "rows": [
                transform_foreclosure_row(row, row.get("quarter", i+1))
                for i, row in enumerate(default_scenario.get("quarterly_projections", []))
            ],
            "final_balance": default_scenario.get("final_balance", ""),
            "final_property_value": default_scenario.get("final_property_value", ""),
            "final_ltv": default_scenario.get("final_ltv", "")
        },
        "scenario_note_rate": {
            "name": note_scenario.get("name", "Note Rate"),
            "interest_rate": note_scenario.get("interest_rate", ""),
            "rows": [
                transform_foreclosure_row(row, row.get("quarter", i+1))
                for i, row in enumerate(note_scenario.get("quarterly_projections", []))
            ],
            "final_balance": note_scenario.get("final_balance", ""),
            "final_property_value": note_scenario.get("final_property_value", ""),
            "final_ltv": note_scenario.get("final_ltv", "")
        },
        "summary": foreclosure.get("summary", {}),
        "ic_talking_points": []
    }

    # -----------------------------------------
    # 13. VALIDATION FLAGS
    # -----------------------------------------
    validations = layer3.get("validations", {})

    sections["validation_flags"] = {
        "summary": validations.get("summary", {}),
        "critical_flags": [],
        "warning_flags": []
    }

    # -----------------------------------------
    # 14. RECOMMENDATION
    # -----------------------------------------
    sections["recommendation"] = {
        "decision": risk.get("overall_risk_score", {}).get("score", "MODERATE"),
        "narrative": risk.get("overall_risk_score", {}).get("recommendation", ""),
        "conditions": [],
        "next_steps": []
    }

    return schema


def main():
    """CLI entry point."""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python transform_layer3_to_schema.py <layer3_json_file> [output_file]")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "schema_output.json"

    # Load Layer 3 data
    with open(input_file, 'r') as f:
        # Handle markdown-wrapped JSON
        content = f.read()
        if content.startswith("#"):
            # Extract JSON from markdown
            import re
            json_match = re.search(r'\[[\s\S]*\]', content)
            if json_match:
                layer3_list = json.loads(json_match.group())
                layer3 = layer3_list[0] if layer3_list else {}
            else:
                raise ValueError("Could not extract JSON from markdown file")
        else:
            layer3_list = json.loads(content)
            layer3 = layer3_list[0] if isinstance(layer3_list, list) else layer3_list

    # Transform
    schema = transform_layer3_to_schema(layer3)

    # Output
    with open(output_file, 'w') as f:
        json.dump(schema, f, indent=2)

    print(f"Schema written to: {output_file}")
    print(f"Total sections: {len(schema.get('sections', {}))}")

    # Summary
    fc = schema.get("sections", {}).get("foreclosure_analysis", {})
    print(f"Foreclosure default rate rows: {len(fc.get('scenario_default_rate', {}).get('rows', []))}")
    print(f"Foreclosure note rate rows: {len(fc.get('scenario_note_rate', {}).get('rows', []))}")


if __name__ == "__main__":
    main()
